FROM python:3.13-alpine
RUN pip install --no-cache-dir PyMySQL==1.1.1
WORKDIR /migrations
COPY . /migrations/
ENV USER=radiusstack
USER 65532:65532
ENTRYPOINT ["python", "/migrations/runner.py"]
CMD ["--migrate"]
