CREATE TABLE IF NOT EXISTS schema_migrations (migration_name VARCHAR(128) NOT NULL PRIMARY KEY, applied_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS radsec_credential_sets (id BIGINT AUTO_INCREMENT PRIMARY KEY, tenant_id INT NOT NULL, label VARCHAR(128) NOT NULL, serial VARCHAR(64) NOT NULL, common_name VARCHAR(128) NOT NULL, certificate_path VARCHAR(255) NOT NULL, private_material_available TINYINT(1) NOT NULL DEFAULT 0, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, revoked_at DATETIME NULL, revoked_reason VARCHAR(255) NULL, UNIQUE KEY uq_radsec_credential_sets_serial (serial), UNIQUE KEY uq_radsec_credential_sets_tenant_label (tenant_id,label), KEY idx_radsec_credential_sets_tenant_active (tenant_id,revoked_at), CONSTRAINT fk_radsec_credential_sets_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS radsec_credential_set_nas (credential_set_id BIGINT NOT NULL,nas_id INT NOT NULL,assigned_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,assigned_by VARCHAR(50) NULL,PRIMARY KEY (credential_set_id,nas_id),KEY idx_radsec_set_nas_nas (nas_id,credential_set_id),CONSTRAINT fk_radsec_set_nas_set FOREIGN KEY (credential_set_id) REFERENCES radsec_credential_sets(id) ON DELETE CASCADE,CONSTRAINT fk_radsec_set_nas_nas FOREIGN KEY (nas_id) REFERENCES nas(id) ON DELETE CASCADE);
ALTER TABLE radsec_clients ADD COLUMN IF NOT EXISTS credential_set_id BIGINT NULL;
ALTER TABLE radsec_clients ADD KEY IF NOT EXISTS idx_radsec_clients_set (credential_set_id);
INSERT IGNORE INTO radsec_credential_sets (tenant_id,label,serial,common_name,certificate_path,created_at,revoked_at) SELECT rc.tenant_id,CONCAT('Migrated NAS ',rc.nas_id,' credential ',rc.id),rc.serial,rc.common_name,rc.certificate_path,rc.issued_at,rc.revoked_at FROM radsec_clients rc;
UPDATE radsec_clients rc JOIN radsec_credential_sets cs ON cs.serial=rc.serial SET rc.credential_set_id=cs.id WHERE rc.credential_set_id IS NULL;
INSERT IGNORE INTO radsec_credential_set_nas (credential_set_id,nas_id,assigned_at) SELECT rc.credential_set_id,rc.nas_id,rc.issued_at FROM radsec_clients rc WHERE rc.credential_set_id IS NOT NULL;
INSERT IGNORE INTO schema_migrations (migration_name) VALUES ('20260919_radsec_credential_sets');
